
def get_mirnas(wildcards):
    point = checkpoints.create_mirna_list.get()
    with open(point.output[0]) as f:
        return [m.strip() for m in f]

rule all:
    input:
        filtered_rpmm = "dataframes/filtered_mirblood_rpmm.csv",
        avg_rpmm_expression = "dataframes/mirblood_avg_expression_per_cell_type_all_samples_rpmm_filtered.csv",
        tsi = "dataframes/mirblood_rpmm_with_tsi.csv",
        mirna_list = "dataframes/mirna_list.txt",
        mirna_plots = expand("plots/{mirna}_boxplot.svg", mirna=get_mirnas)

rule filter_rpmm:
    input:
        rpmm_quantified = "dataframes/std_quantification_rpmm_norm_mirna.csv",
        metadata = "dataframes/mirblood_metadata.csv"
    output: 
        filtered_rpmm = "dataframes/filtered_mirblood_rpmm.csv"
    script:
        "filter_rpmm.py"

rule calculate_avg_expression:
    input:
        filtered_rpmm = "dataframes/filtered_mirblood_rpmm.csv",
        metadata = "dataframes/mirblood_metadata.csv"
    output:
        avg_rpmm_expression = "dataframes/mirblood_avg_expression_per_cell_type_all_samples_rpmm_filtered.csv"
    script:
        "filter_metadata.py"

rule calculate_tsi:
    input:
        avg_rpmm_expression = "dataframes/mirblood_avg_expression_per_cell_type_all_samples_rpmm_filtered.csv"
    output:
        tsi = "dataframes/mirblood_rpmm_with_tsi.csv"
    script:
        "calculate_tsi.py"

checkpoint create_mirna_list:
    input:
        tsi = "dataframes/mirblood_rpmm_with_tsi.csv"
    output:
        mirnas = "dataframes/mirna_list.txt"
    script:
        "create_mirna_list.py"

rule visualize_tissue_specific_miRNAs:
    input:
        metadata = "dataframes/mirblood_metadata.csv",
        filtered_rpmm = "dataframes/filtered_mirblood_rpmm.csv",
    output:
        "plots/{mirna}_boxplot.svg"
    params:
        mirna="{mirna}"
    script:
        "cell_type_specific_mirnas_vis.py"
